alpha: 0.02
corr_threshold: 0.3
edge_types:
- corr
gamma: 0.3
max_iter: 1000
min_module_size: 2
n_components: 10
n_components_cv_folds: 5
n_components_grid:
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 12
- 15
- 20
name: graph_network
normalized_laplacian: true
residualize_covariates:
- RIN
- PMI
- mito_mapping_rate
- percent_assigned
tol: 0.0001
trait_columns:
- Dx
- Age
