deep_split: 2
merge_cut_height: 0.25
min_module_size: 2
name: wgcna_network
network_type: signed
power: null
power_range:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
random_state: 7
residualize_covariates:
- RIN
- PMI
- mito_mapping_rate
- percent_assigned
sft_r2_threshold: 0.85
trait_columns:
- Dx
- Age
